# Generated by Django 4.2.1 on 2023-05-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post/static/team')),
                ('education', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('certificates', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
